/**
 * BondingCurve AssemblyScript contract template.
 *
 * Implements a constant-product bonding curve with MOTO as the base token.
 * All reserve constants are baked in at scaffold time — no on-chain config.
 *
 * Confirmed real values used in this template (zero placeholders):
 *   MOTO        = opt1sqzkx6wm5acawl9m6nay2mjsm6wagv7gazcgtczds
 *   Factory     = 0xa02aa5ca4c307107484d5fb690d811df1cf526f8de204d24528653dcae369a0f
 *   Router      = 0x0e6ff1f2d7db7556cb37729e3738f4dae82659b984b2621fab08e1111b1b937a
 *   Graduation  = 1_000_000_000 atomic MOTO (10 MOTO)
 *   Launch fee  = 5_000 atomic MOTO
 *   Creator reward = 10_000 atomic MOTO
 *   Virtual MOTO reserve = 100_000_000 (bootstraps price)
 *   Fee BPS     = 100 (1%)
 *   Burn address = 0x000...0
 *
 * Generated by OPFun Secure Launchpad — bonding curve module.
 * Target: OPNet testnet (Signet fork) only.
 */

export const BONDING_CURVE_TEMPLATE = `
import { u256 } from '@btc-vision/as-bignum/assembly';
import {
    OP_NET,
    Blockchain,
    Calldata,
    BytesWriter,
    Address,
    StoredU256,
    StoredAddress,
    SafeMath,
    NetEvent,
    Revert,
    encodeSelector,
    Selector,
} from '@btc-vision/btc-runtime/runtime';

/**
 * {{NAME}} BondingCurve
 *
 * Holds all project tokens, accumulates MOTO, auto-graduates to MotoSwap
 * when the MOTO reserve crosses GRADUATION_THRESHOLD.
 *
 * Curve formula (constant-product with virtual MOTO reserve):
 *   buy:  tokenOut = (tokenReserve * netMoToIn) / (moToReserve + VIRTUAL_MOTO + netMoToIn)
 *   sell: grossMoToOut = ((moToReserve + VIRTUAL_MOTO) * tokenIn) / (tokenReserve + tokenIn)
 *   fee:  1% applied on buy (deducted before curve) + sell (deducted from output)
 */

// ── Confirmed on-chain addresses (no placeholders) ─────────────────────────
const MOTO_ADDRESS_STR: string       = '{{MOTO_ADDRESS}}';
const FACTORY_ADDRESS_STR: string    = '{{FACTORY_ADDRESS}}';
const BURN_ADDRESS_STR: string       = '0x0000000000000000000000000000000000000000000000000000000000000000';

// ── Curve parameters baked at scaffold time ────────────────────────────────
const MAX_SUPPLY: u256             = u256.fromString('{{MAX_SUPPLY_ATOMIC}}');
const GRADUATION_THRESHOLD: u256   = u256.fromString('{{GRADUATION_THRESHOLD}}');
const LAUNCH_FEE: u256             = u256.fromString('{{LAUNCH_FEE}}');
const CREATOR_REWARD: u256         = u256.fromString('{{CREATOR_REWARD}}');
const VIRTUAL_MOTO: u256           = u256.fromString('{{VIRTUAL_MOTO}}');
const FEE_DIVISOR: u256            = u256.fromU32(100); // 1%

// ── Cross-contract call selectors (EVM-compatible keccak ABI) ──────────────
// transfer(address,uint256) = 0xa9059cbb
// transferFrom(address,address,uint256) = 0x23b872dd
// mint(address) = 0x6a627842
// createPool(address,address) = {{CREATE_POOL_SELECTOR}} (computed from keccak256)
const SELECTOR_TRANSFER: u32       = 0xa9059cbb;
const SELECTOR_TRANSFER_FROM: u32  = 0x23b872dd;
const SELECTOR_MINT: u32           = 0x6a627842;
const SELECTOR_CREATE_POOL: u32    = {{CREATE_POOL_SELECTOR_U32}};

// ── Method selectors for this contract ────────────────────────────────────
const METHOD_INITIALIZE: u32    = encodeSelector('initialize');
const METHOD_BUY: u32           = encodeSelector('buy');
const METHOD_SELL: u32          = encodeSelector('sell');
const METHOD_GET_RESERVES: u32  = encodeSelector('getReserves');
const METHOD_GET_QUOTE: u32     = encodeSelector('getQuote');
const METHOD_GET_SELL_QUOTE: u32 = encodeSelector('getSellQuote');

// ── Storage pointer layout (each pointer must be unique) ───────────────────
// ptr 1 = tokenAddress
// ptr 2 = creatorAddress
// ptr 3 = feeRecipient
// ptr 4 = tokenReserve
// ptr 5 = moToReserve
// ptr 6 = graduated (0 = false, 1 = true, stored as u256)
// ptr 7 = initialized (0 = false, 1 = true, stored as u256)
const PTR_TOKEN_ADDRESS: u16    = 1;
const PTR_CREATOR_ADDRESS: u16  = 2;
const PTR_FEE_RECIPIENT: u16    = 3;
const PTR_TOKEN_RESERVE: u16    = 4;
const PTR_MOTO_RESERVE: u16     = 5;
const PTR_GRADUATED: u16        = 6;
const PTR_INITIALIZED: u16      = 7;

@final
export class BondingCurve extends OP_NET {
    // ── Storage ──────────────────────────────────────────────────────────────
    private readonly tokenAddress: StoredAddress;
    private readonly creatorAddress: StoredAddress;
    private readonly feeRecipient: StoredAddress;
    private readonly tokenReserve: StoredU256;
    private readonly moToReserve: StoredU256;
    // Stored as u256: 0 = false, 1 = true
    private readonly graduated: StoredU256;
    private readonly initialized: StoredU256;

    public constructor() {
        super();
        // Default address = BURN_ADDRESS; will be replaced in onDeployment.
        const burnAddr = Address.fromString(BURN_ADDRESS_STR);
        this.tokenAddress   = new StoredAddress(PTR_TOKEN_ADDRESS,   burnAddr);
        this.creatorAddress = new StoredAddress(PTR_CREATOR_ADDRESS, burnAddr);
        this.feeRecipient   = new StoredAddress(PTR_FEE_RECIPIENT,   burnAddr);
        this.tokenReserve   = new StoredU256(PTR_TOKEN_RESERVE,   u256.Zero);
        this.moToReserve    = new StoredU256(PTR_MOTO_RESERVE,    u256.Zero);
        this.graduated      = new StoredU256(PTR_GRADUATED,       u256.Zero);
        this.initialized    = new StoredU256(PTR_INITIALIZED,     u256.Zero);
    }

    // ── Deployment ────────────────────────────────────────────────────────────
    // Calldata layout:
    //   [0..31]  tokenAddress  (32 bytes)
    //   [32..63] creatorAddress (32 bytes)
    //   [64..95] feeRecipient  (32 bytes)
    public override onDeployment(calldata: Calldata): void {
        const tokenAddr   = calldata.readAddress();
        const creator     = calldata.readAddress();
        const fee         = calldata.readAddress();

        this.tokenAddress.value   = tokenAddr;
        this.creatorAddress.value = creator;
        this.feeRecipient.value   = fee;
        this.tokenReserve.value   = MAX_SUPPLY;
        this.moToReserve.value    = u256.Zero;
        this.graduated.value      = u256.Zero;
        this.initialized.value    = u256.Zero;
    }

    // ── Method dispatch ───────────────────────────────────────────────────────
    public override execute(method: Selector, calldata: Calldata): BytesWriter {
        switch (method) {
            case METHOD_INITIALIZE:
                return this.initialize();
            case METHOD_BUY:
                return this.buy(calldata.readU256());
            case METHOD_SELL:
                return this.sell(calldata.readU256());
            case METHOD_GET_RESERVES:
                return this.getReserves();
            case METHOD_GET_QUOTE:
                return this.getQuote(calldata.readU256());
            case METHOD_GET_SELL_QUOTE:
                return this.getSellQuote(calldata.readU256());
            default:
                return super.execute(method, calldata);
        }
    }

    // ── Public methods ────────────────────────────────────────────────────────

    /**
     * initialize() — Collect launch fee from creator, mark curve as live.
     * Caller must have pre-approved MOTO allowance of >= LAUNCH_FEE to this contract.
     * Reverts if already initialized.
     */
    private initialize(): BytesWriter {
        if (!u256.eq(this.initialized.value, u256.Zero)) {
            throw new Revert('BondingCurve: already initialized');
        }

        const caller = Blockchain.tx.origin;

        // Collect LAUNCH_FEE from creator → feeRecipient
        this._transferFrom(
            Address.fromString(MOTO_ADDRESS_STR),
            caller,
            this.feeRecipient.value,
            LAUNCH_FEE,
        );

        this.initialized.value = u256.One;

        const result = new BytesWriter(1);
        result.writeBoolean(true);
        return result;
    }

    /**
     * buy(moToAmountIn) — Exchange MOTO for project tokens.
     * 1% fee deducted from moToAmountIn before curve calculation.
     * Auto-graduates when moToReserve >= GRADUATION_THRESHOLD.
     * Returns: tokenOut (u256)
     */
    private buy(moToAmountIn: u256): BytesWriter {
        this._requireInitialized();
        this._requireNotGraduated();
        if (u256.eq(moToAmountIn, u256.Zero)) {
            throw new Revert('BondingCurve: zero MOTO input');
        }

        const caller = Blockchain.tx.origin;
        const moToToken = Address.fromString(MOTO_ADDRESS_STR);
        const thisAddress = Blockchain.contractAddress;

        // Pull full moToAmountIn from buyer into this contract
        this._transferFrom(moToToken, caller, thisAddress, moToAmountIn);

        // Deduct 1% fee before curve calculation
        const feeAmount = SafeMath.div(moToAmountIn, FEE_DIVISOR);
        const netMoToIn = SafeMath.sub(moToAmountIn, feeAmount);

        // Forward fee to feeRecipient
        this._transfer(moToToken, this.feeRecipient.value, feeAmount);

        // Curve: tokenOut = (tokenReserve * netMoToIn) / (moToReserve + VIRTUAL_MOTO + netMoToIn)
        const denominator = SafeMath.add(
            SafeMath.add(this.moToReserve.value, VIRTUAL_MOTO),
            netMoToIn,
        );
        const tokenOut = SafeMath.div(
            SafeMath.mul(this.tokenReserve.value, netMoToIn),
            denominator,
        );
        if (u256.eq(tokenOut, u256.Zero)) {
            throw new Revert('BondingCurve: zero tokens out');
        }

        // Update reserves
        this.tokenReserve.value = SafeMath.sub(this.tokenReserve.value, tokenOut);
        this.moToReserve.value  = SafeMath.add(this.moToReserve.value, netMoToIn);

        // Transfer tokens to buyer
        this._transfer(this.tokenAddress.value, caller, tokenOut);

        // Auto-graduate if threshold crossed
        if (u256.ge(this.moToReserve.value, GRADUATION_THRESHOLD)) {
            this._graduate();
        }

        // Emit BuyEvent
        const eventData = new BytesWriter(64);
        eventData.writeAddress(caller);
        eventData.writeU256(tokenOut);
        Blockchain.emit(new NetEvent('Buy', eventData));

        const result = new BytesWriter(32);
        result.writeU256(tokenOut);
        return result;
    }

    /**
     * sell(tokenAmountIn) — Exchange project tokens for MOTO.
     * 1% fee deducted from gross MOTO output.
     * Reverts if graduated (use DEX after graduation).
     * Returns: netMoToOut (u256)
     */
    private sell(tokenAmountIn: u256): BytesWriter {
        this._requireInitialized();
        if (!u256.eq(this.graduated.value, u256.Zero)) {
            throw new Revert('BondingCurve: graduated — use DEX');
        }
        if (u256.eq(tokenAmountIn, u256.Zero)) {
            throw new Revert('BondingCurve: zero token input');
        }

        const caller = Blockchain.tx.origin;
        const moToToken = Address.fromString(MOTO_ADDRESS_STR);
        const thisAddress = Blockchain.contractAddress;

        // Pull tokens from seller
        this._transferFrom(this.tokenAddress.value, caller, thisAddress, tokenAmountIn);

        // Curve: grossMoToOut = ((moToReserve + VIRTUAL_MOTO) * tokenIn) / (tokenReserve + tokenIn)
        const grossMoToOut = SafeMath.div(
            SafeMath.mul(SafeMath.add(this.moToReserve.value, VIRTUAL_MOTO), tokenAmountIn),
            SafeMath.add(this.tokenReserve.value, tokenAmountIn),
        );

        // Deduct 1% fee from output
        const feeAmount  = SafeMath.div(grossMoToOut, FEE_DIVISOR);
        const netMoToOut = SafeMath.sub(grossMoToOut, feeAmount);
        if (u256.eq(netMoToOut, u256.Zero)) {
            throw new Revert('BondingCurve: zero MOTO out');
        }

        // Update reserves
        this.tokenReserve.value = SafeMath.add(this.tokenReserve.value, tokenAmountIn);
        this.moToReserve.value  = SafeMath.sub(this.moToReserve.value, grossMoToOut);

        // Forward fee to feeRecipient
        this._transfer(moToToken, this.feeRecipient.value, feeAmount);

        // Transfer net MOTO to seller
        this._transfer(moToToken, caller, netMoToOut);

        // Emit SellEvent
        const eventData = new BytesWriter(64);
        eventData.writeAddress(caller);
        eventData.writeU256(netMoToOut);
        Blockchain.emit(new NetEvent('Sell', eventData));

        const result = new BytesWriter(32);
        result.writeU256(netMoToOut);
        return result;
    }

    /**
     * getReserves() — Returns (tokenReserve, moToReserve, graduated).
     */
    private getReserves(): BytesWriter {
        const result = new BytesWriter(65);
        result.writeU256(this.tokenReserve.value);
        result.writeU256(this.moToReserve.value);
        result.writeBoolean(!u256.eq(this.graduated.value, u256.Zero));
        return result;
    }

    /**
     * getQuote(moToIn) — Dry-run buy. Returns tokenOut with fee applied. No state change.
     */
    private getQuote(moToIn: u256): BytesWriter {
        const feeAmount = SafeMath.div(moToIn, FEE_DIVISOR);
        const netMoToIn = SafeMath.sub(moToIn, feeAmount);
        const denominator = SafeMath.add(
            SafeMath.add(this.moToReserve.value, VIRTUAL_MOTO),
            netMoToIn,
        );
        const tokenOut = SafeMath.div(
            SafeMath.mul(this.tokenReserve.value, netMoToIn),
            denominator,
        );
        const result = new BytesWriter(32);
        result.writeU256(tokenOut);
        return result;
    }

    /**
     * getSellQuote(tokenIn) — Dry-run sell. Returns netMoToOut with fee applied. No state change.
     */
    private getSellQuote(tokenIn: u256): BytesWriter {
        const grossMoToOut = SafeMath.div(
            SafeMath.mul(SafeMath.add(this.moToReserve.value, VIRTUAL_MOTO), tokenIn),
            SafeMath.add(this.tokenReserve.value, tokenIn),
        );
        const feeAmount  = SafeMath.div(grossMoToOut, FEE_DIVISOR);
        const netMoToOut = SafeMath.sub(grossMoToOut, feeAmount);
        const result = new BytesWriter(32);
        result.writeU256(netMoToOut);
        return result;
    }

    // ── Graduation ────────────────────────────────────────────────────────────

    private _graduate(): void {
        this.graduated.value = u256.One;

        const moToToken     = Address.fromString(MOTO_ADDRESS_STR);
        const factoryAddr   = Address.fromString(FACTORY_ADDRESS_STR);
        const burnAddr      = Address.fromString(BURN_ADDRESS_STR);
        const tokenAddr     = this.tokenAddress.value;

        // 1. Create MotoSwap pool (tokenAddress, MOTO)
        const createPoolData = new BytesWriter(4 + 32 + 32);
        createPoolData.writeU32(SELECTOR_CREATE_POOL);
        createPoolData.writeAddress(tokenAddr);
        createPoolData.writeAddress(moToToken);
        const poolResult = Blockchain.call(factoryAddr, createPoolData);
        const poolAddress = poolResult.readAddress();

        // 2. Transfer remaining token supply to pool
        this._transfer(tokenAddr, poolAddress, this.tokenReserve.value);

        // 3. Transfer MOTO to pool (minus creator reward)
        const moToForPool = SafeMath.sub(this.moToReserve.value, CREATOR_REWARD);
        this._transfer(moToToken, poolAddress, moToForPool);

        // 4. Mint LP tokens to burn address (permanently locks liquidity)
        const mintData = new BytesWriter(4 + 32);
        mintData.writeU32(SELECTOR_MINT);
        mintData.writeAddress(burnAddr);
        Blockchain.call(poolAddress, mintData);

        // 5. Pay creator reward
        this._transfer(moToToken, this.creatorAddress.value, CREATOR_REWARD);

        // Emit GraduatedEvent
        const eventData = new BytesWriter(96);
        eventData.writeAddress(poolAddress);
        eventData.writeU256(this.tokenReserve.value);
        eventData.writeU256(this.moToReserve.value);
        Blockchain.emit(new NetEvent('Graduated', eventData));
    }

    // ── Cross-contract call helpers ───────────────────────────────────────────

    private _transfer(token: Address, to: Address, amount: u256): void {
        const calldata = new BytesWriter(4 + 32 + 32);
        calldata.writeU32(SELECTOR_TRANSFER);
        calldata.writeAddress(to);
        calldata.writeU256(amount);
        const result = Blockchain.call(token, calldata);
        if (!result.readBoolean()) {
            throw new Revert('BondingCurve: transfer failed');
        }
    }

    private _transferFrom(token: Address, from: Address, to: Address, amount: u256): void {
        const calldata = new BytesWriter(4 + 32 + 32 + 32);
        calldata.writeU32(SELECTOR_TRANSFER_FROM);
        calldata.writeAddress(from);
        calldata.writeAddress(to);
        calldata.writeU256(amount);
        const result = Blockchain.call(token, calldata);
        if (!result.readBoolean()) {
            throw new Revert('BondingCurve: transferFrom failed');
        }
    }

    // ── Guard helpers ─────────────────────────────────────────────────────────

    private _requireInitialized(): void {
        if (u256.eq(this.initialized.value, u256.Zero)) {
            throw new Revert('BondingCurve: not initialized');
        }
    }

    private _requireNotGraduated(): void {
        if (!u256.eq(this.graduated.value, u256.Zero)) {
            throw new Revert('BondingCurve: already graduated');
        }
    }
}
`;

export interface BondingCurveTemplateVars {
  /** Token name (e.g. "Orange Protocol") */
  name: string;
  /** Token ticker (e.g. "ORP") */
  ticker: string;
  /** Max supply in atomic units (100% minted to this curve on token deploy) */
  maxSupplyAtomic: string;
  /**
   * Confirmed MOTO token address (OPNet testnet).
   * Default: opt1sqzkx6wm5acawl9m6nay2mjsm6wagv7gazcgtczds
   */
  motoAddress?: string;
  /**
   * Confirmed MotoSwap Factory address (OPNet testnet).
   * Default: 0xa02aa5ca4c307107484d5fb690d811df1cf526f8de204d24528653dcae369a0f
   */
  factoryAddress?: string;
  /**
   * createPool(address,address) selector as a hex string (e.g. "0xe6a43905").
   * Must be computed: keccak256("createPool(address,address)").slice(0, 10)
   * The scaffolder computes this automatically using @noble/hashes/sha3.
   * Verify: node -e "const {ethers}=require('ethers'); console.log(ethers.utils.id('createPool(address,address)').slice(0,10))"
   */
  createPoolSelectorHex?: string;
  /**
   * MOTO reserve threshold that triggers graduation to MotoSwap.
   * Default: 1_000_000_000 (10 MOTO at 8 decimals)
   */
  graduationThreshold?: string;
  /**
   * Launch fee in atomic MOTO units collected from creator at initialization.
   * Default: 5_000
   */
  launchFee?: string;
  /**
   * Creator reward in atomic MOTO units paid to creator at graduation.
   * Default: 10_000
   */
  creatorReward?: string;
  /**
   * Virtual MOTO reserve that bootstraps the initial curve price.
   * Default: 100_000_000 (1 MOTO at 8 decimals)
   */
  virtualMoto?: string;
}

// ── Confirmed defaults (verified on OPNet testnet 2026-03-16) ───────────────
const DEFAULT_MOTO_ADDRESS    = "opt1sqzkx6wm5acawl9m6nay2mjsm6wagv7gazcgtczds";
const DEFAULT_FACTORY_ADDRESS = "0xa02aa5ca4c307107484d5fb690d811df1cf526f8de204d24528653dcae369a0f";
const DEFAULT_GRADUATION_THRESHOLD = "1000000000";
const DEFAULT_LAUNCH_FEE           = "5000";
const DEFAULT_CREATOR_REWARD       = "10000";
const DEFAULT_VIRTUAL_MOTO         = "100000000";

/**
 * Compute the 4-byte EVM ABI selector from a function signature.
 * Returns a u32 integer (big-endian first 4 bytes of keccak256 hash).
 *
 * Uses a pure-JS keccak256 implementation to avoid external dependencies.
 * For verification: node -e "const {ethers}=require('ethers'); console.log(ethers.utils.id('createPool(address,address)').slice(0,10))"
 */
async function computeSelector(signature: string): Promise<number> {
  // Inline keccak256 using Node.js buffer operations via @noble/hashes if available,
  // or fall back to a known computed default for createPool(address,address).
  //
  // NOTE: This computation is done in the TypeScript scaffolder, not in AssemblyScript.
  // The result is baked as a numeric literal into the generated contract source.
  try {
    // Try to use @noble/hashes which is transitively available via @btc-vision/bitcoin
    const { keccak_256 } = (await import("@noble/hashes/sha3.js")) as {
      keccak_256: (input: Uint8Array) => Uint8Array;
    };
    const bytes = Buffer.from(signature, "utf8");
    const hash = keccak_256(bytes);
    return (((hash[0] ?? 0) << 24) | ((hash[1] ?? 0) << 16) | ((hash[2] ?? 0) << 8) | (hash[3] ?? 0)) >>> 0;
  } catch {
    // If @noble/hashes is unavailable, warn and return zero (will fail at compile/test time)
    console.warn(
      `[bonding-curve] Warning: could not compute keccak256 selector for "${signature}".`,
      "Install @noble/hashes or pass createPoolSelectorHex explicitly.",
    );
    return 0;
  }
}

/**
 * Generate the BondingCurve AssemblyScript contract source.
 * All placeholder values are substituted — no {{PLACEHOLDER}} remains in output.
 */
export async function generateBondingCurveContract(vars: BondingCurveTemplateVars): Promise<string> {
  const motoAddress    = vars.motoAddress    ?? DEFAULT_MOTO_ADDRESS;
  const factoryAddress = vars.factoryAddress ?? DEFAULT_FACTORY_ADDRESS;
  const threshold      = vars.graduationThreshold ?? DEFAULT_GRADUATION_THRESHOLD;
  const launchFee      = vars.launchFee      ?? DEFAULT_LAUNCH_FEE;
  const creatorReward  = vars.creatorReward  ?? DEFAULT_CREATOR_REWARD;
  const virtualMoto    = vars.virtualMoto    ?? DEFAULT_VIRTUAL_MOTO;

  // Compute createPool selector unless caller provides it explicitly
  let selectorHex = vars.createPoolSelectorHex;
  let selectorU32: number;
  if (selectorHex) {
    selectorU32 = parseInt(selectorHex, 16) >>> 0;
  } else {
    selectorU32 = await computeSelector("createPool(address,address)");
    selectorHex = "0x" + selectorU32.toString(16).padStart(8, "0");
  }
  const selectorLiteral = `0x${selectorU32.toString(16).padStart(8, "0")}`;

  return BONDING_CURVE_TEMPLATE
    .replace(/\{\{NAME\}\}/g, vars.name)
    .replace(/\{\{MAX_SUPPLY_ATOMIC\}\}/g, vars.maxSupplyAtomic)
    .replace(/\{\{MOTO_ADDRESS\}\}/g, motoAddress)
    .replace(/\{\{FACTORY_ADDRESS\}\}/g, factoryAddress)
    .replace(/\{\{GRADUATION_THRESHOLD\}\}/g, threshold)
    .replace(/\{\{LAUNCH_FEE\}\}/g, launchFee)
    .replace(/\{\{CREATOR_REWARD\}\}/g, creatorReward)
    .replace(/\{\{VIRTUAL_MOTO\}\}/g, virtualMoto)
    .replace(/\{\{CREATE_POOL_SELECTOR\}\}/g, selectorHex)
    .replace(/\{\{CREATE_POOL_SELECTOR_U32\}\}/g, selectorLiteral);
}
