/**
 * AssemblyScript entry point template for BondingCurve contracts.
 * Generated by OPFun Secure Launchpad — DO NOT EDIT MANUALLY.
 * Target: OP_NET testnet only.
 */

export const BONDING_CURVE_ENTRY_TEMPLATE = `
import { Blockchain } from '@btc-vision/btc-runtime/runtime';
import { revertOnError } from '@btc-vision/btc-runtime/runtime/abort/abort';
import { BondingCurve } from './BondingCurve';

// ── Entry point ───────────────────────────────────────────────────────────
// Do NOT add custom logic here. Only the contract class assignment is allowed.
Blockchain.contract = (): BondingCurve => {
    return new BondingCurve();
};

// ── Required re-exports ───────────────────────────────────────────────────
export * from '@btc-vision/btc-runtime/runtime/exports';

// ── Abort handler (MANDATORY) ─────────────────────────────────────────────
export function abort(
    message: string,
    fileName: string,
    line: u32,
    column: u32,
): void {
    revertOnError(message, fileName, line, column);
}
`;

export const BONDING_CURVE_PACKAGE_JSON_TEMPLATE = `{
  "name": "{{SLUG}}-curve-contract",
  "version": "1.0.0",
  "description": "{{NAME}} BondingCurve OP_NET contract — OPNet testnet",
  "scripts": {
    "build": "asc src/index.ts --config asconfig.json --target debug",
    "build:release": "asc src/index.ts --config asconfig.json --target release",
    "clean": "rm -rf build"
  },
  "dependencies": {
    "@btc-vision/as-bignum": "0.1.2",
    "@btc-vision/btc-runtime": "1.10.12"
  },
  "devDependencies": {
    "@btc-vision/assemblyscript": "^0.29.2",
    "@btc-vision/opnet-transform": "1.2.0",
    "@assemblyscript/loader": "^0.28.9"
  },
  "overrides": {
    "@noble/hashes": "2.0.1"
  }
}
`;

export const BONDING_CURVE_ASCONFIG_JSON = `{
  "targets": {
    "debug": {
      "outFile": "build/BondingCurve.wasm",
      "textFile": "build/BondingCurve.wat"
    },
    "release": {
      "outFile": "build/BondingCurve.wasm",
      "textFile": "build/BondingCurve.wat"
    }
  },
  "options": {
    "transform": "@btc-vision/opnet-transform",
    "sourceMap": false,
    "optimizeLevel": 3,
    "shrinkLevel": 1,
    "converge": true,
    "noAssert": false,
    "enable": [
      "sign-extension",
      "mutable-globals",
      "nontrapping-f2i",
      "bulk-memory",
      "simd",
      "reference-types",
      "multi-value"
    ],
    "runtime": "stub",
    "memoryBase": 0,
    "initialMemory": 1,
    "exportStart": "start",
    "use": [
      "abort=index/abort"
    ]
  }
}
`;

/**
 * Generate the BondingCurve AS entry point (index.ts).
 */
export function generateBondingCurveEntry(): string {
  return BONDING_CURVE_ENTRY_TEMPLATE;
}

export function generateBondingCurvePackageJson(vars: { slug: string; name: string }): string {
  return BONDING_CURVE_PACKAGE_JSON_TEMPLATE
    .replace(/\{\{SLUG\}\}/g, vars.slug)
    .replace(/\{\{NAME\}\}/g, vars.name);
}

export function generateBondingCurveAsconfigJson(): string {
  return BONDING_CURVE_ASCONFIG_JSON;
}
