/**
 * AssemblyScript entry point template for OP_20 contracts.
 * Generated by OPFun Secure Launchpad — DO NOT EDIT MANUALLY.
 * Target: OP_NET testnet only.
 */

export const CONTRACT_ENTRY_TEMPLATE = `
import { Blockchain } from '@btc-vision/btc-runtime/runtime';
import { revertOnError } from '@btc-vision/btc-runtime/runtime/abort/abort';
import { {{CLASS_NAME}} } from './{{TICKER}}';

// ── Entry point ───────────────────────────────────────────────────────────
// Do NOT add custom logic here. Only the contract class assignment is allowed.
Blockchain.contract = (): {{CLASS_NAME}} => {
    return new {{CLASS_NAME}}();
};

// ── Required re-exports ───────────────────────────────────────────────────
export * from '@btc-vision/btc-runtime/runtime/exports';

// ── Abort handler (MANDATORY) ─────────────────────────────────────────────
export function abort(
    message: string,
    fileName: string,
    line: u32,
    column: u32,
): void {
    revertOnError(message, fileName, line, column);
}
`;

export const CONTRACT_PACKAGE_JSON_TEMPLATE = `{
  "name": "{{SLUG}}-contract",
  "version": "1.0.0",
  "description": "{{NAME}} ({{TICKER}}) OP_20 fixed-supply token — OPNet testnet",
  "scripts": {
    "build": "asc src/index.ts --config asconfig.json --target debug",
    "build:release": "asc src/index.ts --config asconfig.json --target release",
    "clean": "rm -rf build"
  },
  "dependencies": {
    "@btc-vision/as-bignum": "0.1.2",
    "@btc-vision/btc-runtime": "rc"
  },
  "devDependencies": {
    "@btc-vision/assemblyscript": "^0.29.2",
    "@btc-vision/opnet-transform": "1.1.0",
    "@assemblyscript/loader": "latest"
  },
  "overrides": {
    "@noble/hashes": "2.0.1"
  }
}
`;

export const CONTRACT_ASCONFIG_JSON = `{
  "targets": {
    "debug": {
      "outFile": "build/{{TICKER}}.wasm",
      "textFile": "build/{{TICKER}}.wat"
    },
    "release": {
      "outFile": "build/{{TICKER}}.wasm",
      "textFile": "build/{{TICKER}}.wat"
    }
  },
  "options": {
    "transform": "@btc-vision/opnet-transform",
    "sourceMap": false,
    "optimizeLevel": 3,
    "shrinkLevel": 1,
    "converge": true,
    "noAssert": false,
    "enable": [
      "sign-extension",
      "mutable-globals",
      "nontrapping-f2i",
      "bulk-memory",
      "simd",
      "reference-types",
      "multi-value"
    ],
    "runtime": "stub",
    "memoryBase": 0,
    "initialMemory": 1,
    "exportStart": "start",
    "use": [
      "abort=index/abort"
    ]
  }
}
`;

export function generateContractEntry(vars: { className: string; ticker: string }): string {
  return CONTRACT_ENTRY_TEMPLATE
    .replace(/\{\{CLASS_NAME\}\}/g, vars.className)
    .replace(/\{\{TICKER\}\}/g, vars.ticker);
}

export function generateContractPackageJson(vars: {
  slug: string;
  name: string;
  ticker: string;
}): string {
  return CONTRACT_PACKAGE_JSON_TEMPLATE
    .replace(/\{\{SLUG\}\}/g, vars.slug)
    .replace(/\{\{NAME\}\}/g, vars.name)
    .replace(/\{\{TICKER\}\}/g, vars.ticker);
}

export function generateAsconfigJson(vars: { ticker: string }): string {
  return CONTRACT_ASCONFIG_JSON.replace(/\{\{TICKER\}\}/g, vars.ticker);
}
