/**
 * Standalone TypeScript deploy script template.
 * Generated by OPFun Secure Launchpad — ready to run with your own wallet.
 * Usage: OPNET_MNEMONIC="..." ts-node deploy.ts
 * SAFETY: Never commit secrets. Set OPNET_MNEMONIC via environment variable only.
 */

export const DEPLOY_SCRIPT_TEMPLATE = `#!/usr/bin/env ts-node
/**
 * Deploy {{NAME}} ({{TICKER}}) to OPNet Testnet
 * Generated: {{GENERATED_AT}}
 * Build Hash: {{BUILD_HASH}}
 *
 * Prerequisites:
 *   1. Install deps:  npm install
 *   2. Compile WASM:  npm run build  (inside contract/ directory)
 *   3. Fund wallet:   send testnet BTC to your p2tr address (see DEPLOY.md)
 *   4. Set mnemonic:  export OPNET_MNEMONIC="your 24 word phrase..."
 *   5. Run:           npx ts-node deploy.ts
 *
 * SAFETY: Testnet only. Never paste seed phrases or private keys in this file.
 */
import {
    Mnemonic,
    TransactionFactory,
    ChallengeSolution,
    OPNetLimitedProvider,
    type UTXO,
    type RawChallenge,
} from '@btc-vision/transaction';
import { networks } from '@btc-vision/bitcoin';
import * as fs from 'node:fs';
import * as path from 'node:path';

// ── Config ────────────────────────────────────────────────────────────────
const NETWORK = networks.opnetTestnet;
const RPC_URL = 'https://testnet.opnet.org';
const WASM_PATH = path.resolve(__dirname, 'contract/build/{{TICKER}}.wasm');

const mnemonic_phrase = process.env['OPNET_MNEMONIC'];
if (!mnemonic_phrase) {
    console.error('Error: OPNET_MNEMONIC environment variable is not set.');
    console.error('Export it: export OPNET_MNEMONIC="word1 word2 ... word24"');
    process.exit(1);
}

// ── Main ──────────────────────────────────────────────────────────────────
async function deploy(): Promise<void> {
    const mnemonic = new Mnemonic(mnemonic_phrase!, '', NETWORK);
    const wallet = mnemonic.derive(0);

    console.log('Deployer address:', wallet.p2tr);
    console.log('Network: OPNet Testnet (Signet fork)');

    if (!fs.existsSync(WASM_PATH)) {
        console.error('WASM not found at:', WASM_PATH);
        console.error('Run: cd contract && npm install && npm run build');
        process.exit(1);
    }

    const bytecode: Uint8Array = fs.readFileSync(WASM_PATH);
    console.log('Contract size:', bytecode.length, 'bytes');

    const provider = new OPNetLimitedProvider(RPC_URL);

    // Fetch UTXOs (need at least 100,000 sat)
    console.log('Fetching UTXOs...');
    const utxos: UTXO[] = await provider.fetchUTXO({
        address: wallet.p2tr,
        minAmount: 100_000n,
        requestedAmount: 600_000n,
    });

    if (utxos.length === 0) {
        console.error('No UTXOs found. Fund your testnet wallet:');
        console.error('  Address:', wallet.p2tr);
        console.error('  Faucet:  https://faucet.opnet.org (or any Signet faucet)');
        process.exit(1);
    }
    console.log('UTXOs found:', utxos.length);

    // Get challenge from node
    console.log('Fetching epoch challenge...');
    const epochTemplate = await provider.getEpochTemplate();
    const latestEpoch = await provider.getLatestEpoch();

    // Build challenge solution (basic mining for testnet)
    const rawChallenge: RawChallenge = {
        epochNumber: latestEpoch.epochNumber,
        mldsaPublicKey: '0x' + Buffer.from(wallet.mldsaKeypair.publicKey).toString('hex'),
        legacyPublicKey: '0x' + Buffer.from(wallet.address.originalPublicKey!).toString('hex'),
        solution: latestEpoch.proposer?.solution ?? '0x00',
        salt: latestEpoch.proposer?.salt ?? '0x00',
        graffiti: '0x4f504e4554', // "OPNET" in hex
        difficulty: 1,
        verification: {
            epochHash: latestEpoch.epochHash,
            epochRoot: latestEpoch.epochRoot,
            targetHash: latestEpoch.targetHash,
            targetChecksum: epochTemplate.epochTarget,
            startBlock: latestEpoch.startBlock,
            endBlock: latestEpoch.endBlock,
            proofs: latestEpoch.proofs,
        },
    };

    const challenge = new ChallengeSolution(rawChallenge);

    // Build and sign deployment
    console.log('Building deployment transaction...');
    const factory = new TransactionFactory();
    const result = await factory.signDeployment({
        signer: wallet.keypair,
        mldsaSigner: wallet.mldsaKeypair,
        network: NETWORK,
        from: wallet.p2tr,
        bytecode,
        utxos,
        challenge,
        feeRate: 5,
        priorityFee: 330n,
        gasSatFee: 330n,
    });

    console.log('\\n─────────────────────────────────────────');
    console.log('Contract address:', result.contractAddress);
    console.log('Contract pubkey: ', result.contractPubKey);
    console.log('─────────────────────────────────────────');
    console.log('Broadcasting funding TX...');
    const fundingTx = await provider.broadcast(result.transaction[0]!);
    console.log('Funding TX:', fundingTx);

    console.log('Broadcasting deployment TX...');
    const deployTx = await provider.broadcast(result.transaction[1]!);
    console.log('Deploy TX:', deployTx);

    console.log('\\n✓ Deployed successfully!');
    console.log('  Contract:', result.contractAddress);
    console.log('  TX:      ', deployTx);
    console.log('  Explorer: https://testnet.opnet.org/contract/' + result.contractAddress);

    // Output machine-readable result for the API to parse
    const deployResult = {
        contractAddress: result.contractAddress,
        contractPubKey: result.contractPubKey,
        deployTx,
        fundingTx,
        network: 'testnet',
        buildHash: '{{BUILD_HASH}}',
    };
    fs.writeFileSync(
        path.resolve(__dirname, 'deploy-result.json'),
        JSON.stringify(deployResult, null, 2),
    );
    console.log('\\nResult saved to deploy-result.json');

    // Clean up
    mnemonic.zeroize();
    wallet.zeroize();
}

deploy().catch((err: unknown) => {
    console.error('Deploy failed:', err);
    process.exit(1);
});
`;

export const DEPLOY_PACKAGE_JSON = `{
  "name": "deploy-{{SLUG}}",
  "version": "1.0.0",
  "type": "module",
  "description": "Deploy script for {{NAME}} ({{TICKER}})",
  "scripts": {
    "deploy": "npx ts-node deploy.ts"
  },
  "dependencies": {
    "@btc-vision/bitcoin": "rc",
    "@btc-vision/bip32": "latest",
    "@btc-vision/ecpair": "latest",
    "@btc-vision/transaction": "rc",
    "opnet": "rc"
  },
  "devDependencies": {
    "@types/node": "latest",
    "ts-node": "latest",
    "typescript": "latest"
  },
  "overrides": {
    "@noble/hashes": "2.0.1"
  }
}
`;

export const DEPLOY_README_TEMPLATE = `# Deploy {{NAME}} ({{TICKER}}) to OPNet Testnet

**Generated:** {{GENERATED_AT}}
**Build hash:** \`{{BUILD_HASH}}\`

---

## Quick deploy

### 1. Compile the contract

\`\`\`bash
cd contract
npm install
npm run build
# → Outputs: contract/build/{{TICKER}}.wasm
\`\`\`

### 2. Get testnet BTC

Fund your deployer wallet (you'll need ~100,000 sat):

\`\`\`bash
# First, find your address:
npx ts-node -e "
const { Mnemonic } = require('@btc-vision/transaction');
const { networks } = require('@btc-vision/bitcoin');
const m = new Mnemonic(process.env.OPNET_MNEMONIC, '', networks.opnetTestnet);
const w = m.derive(0);
console.log('Address:', w.p2tr);
m.zeroize(); w.zeroize();
"
\`\`\`

Then get testnet BTC from a Signet faucet (OPNet uses Bitcoin Signet):
- https://faucet.opnet.org
- https://signet.bc-2.jp/

### 3. Set your mnemonic

\`\`\`bash
export OPNET_MNEMONIC="word1 word2 word3 ... word24"
\`\`\`

⚠️  NEVER commit your mnemonic. Environment variable only.

### 4. Run the deploy script

\`\`\`bash
npm install
npx ts-node deploy.ts
\`\`\`

Expected output:
\`\`\`
Contract address: bcrt1p...
Deploy TX: <txid>
✓ Deployed successfully!
\`\`\`

### 5. After deployment

Copy the contract address and deploy TX, then update the project via the OPFun API:

\`\`\`bash
curl -X POST http://localhost:3001/projects/{{PROJECT_ID}}/confirm-deploy \\
  -H "Content-Type: application/json" \\
  -H "X-Admin-Secret: YOUR_ADMIN_SECRET" \\
  -d '{
    "contractAddress": "bcrt1p...",
    "deployTx": "<txid>",
    "buildHash": "{{BUILD_HASH}}"
  }'
\`\`\`

---

## Security defaults

This contract has **safe defaults enforced**:

| Property | Value | Risk |
|----------|-------|------|
| canMint | false | LOW — fixed supply |
| canPause | false | LOW — always transferable |
| hasAdminKey | false | LOW — no privileged addresses |
| canUpgrade | false | LOW — logic is permanent |

---

## Network

**TESTNET ONLY.** Target: OPNet Testnet (Bitcoin Signet fork)
- RPC: https://testnet.opnet.org
- Must use \`networks.opnetTestnet\` from \`@btc-vision/bitcoin\`
- NEVER use \`networks.testnet\` — that is Bitcoin Testnet4 (incompatible)
`;

export function generateDeployScript(vars: {
  name: string;
  ticker: string;
  buildHash: string;
  generatedAt: string;
}): string {
  return DEPLOY_SCRIPT_TEMPLATE
    .replace(/\{\{NAME\}\}/g, vars.name)
    .replace(/\{\{TICKER\}\}/g, vars.ticker)
    .replace(/\{\{BUILD_HASH\}\}/g, vars.buildHash)
    .replace(/\{\{GENERATED_AT\}\}/g, vars.generatedAt);
}

export function generateDeployPackageJson(vars: { slug: string; name: string; ticker: string }): string {
  return DEPLOY_PACKAGE_JSON
    .replace(/\{\{SLUG\}\}/g, vars.slug)
    .replace(/\{\{NAME\}\}/g, vars.name)
    .replace(/\{\{TICKER\}\}/g, vars.ticker);
}

export function generateDeployReadme(vars: {
  name: string;
  ticker: string;
  slug: string;
  buildHash: string;
  generatedAt: string;
  projectId: string;
}): string {
  return DEPLOY_README_TEMPLATE
    .replace(/\{\{NAME\}\}/g, vars.name)
    .replace(/\{\{TICKER\}\}/g, vars.ticker)
    .replace(/\{\{BUILD_HASH\}\}/g, vars.buildHash)
    .replace(/\{\{GENERATED_AT\}\}/g, vars.generatedAt)
    .replace(/\{\{PROJECT_ID\}\}/g, vars.projectId);
}
