/**
 * OP_20 Fixed-Supply Token Template
 *
 * Safe defaults enforced:
 *  - Fixed max supply (no mint after deployment)
 *  - No pause / transfer restrictions
 *  - No admin / owner keys
 *  - No upgrade mechanism
 *  - All supply minted to deployer at deployment
 *
 * Generated by OPFun Secure Launchpad (Milestone 2).
 * Target: OP_NET testnet only.
 */

export const OP20_FIXED_TEMPLATE = `
import { u256 } from '@btc-vision/as-bignum/assembly';
import {
    OP20,
    OP20InitParameters,
    Blockchain,
    Calldata,
    BytesWriter,
} from '@btc-vision/btc-runtime/runtime';

/**
 * {{NAME}} ({{TICKER}})
 *
 * Fixed-supply OP_20 token.
 * Max supply: {{MAX_SUPPLY_ATOMIC}} ({{MAX_SUPPLY_HUMAN}} with {{DECIMALS}} decimals)
 *
 * Security profile:
 *  canMint    = false  — supply is permanently fixed
 *  canPause   = false  — transfers are always enabled
 *  hasAdmin   = false  — no privileged addresses
 *  canUpgrade = false  — no upgrade mechanism
 */
@final
export class {{CLASS_NAME}} extends OP20 {
    public constructor() {
        super();
    }

    public override onDeployment(calldata: Calldata): void {
        const maxSupply = u256.fromString('{{MAX_SUPPLY_ATOMIC}}');
        this.instantiate(
            new OP20InitParameters(
                maxSupply,
                {{DECIMALS}},
                '{{NAME}}',
                '{{TICKER}}',
                '{{ICON_URL}}',
            ),
        );
        // Mint entire supply to deployer at launch — no further minting possible
        this._mint(Blockchain.tx.origin, maxSupply);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // No mint()   — fixed supply, cannot create new tokens
    // No pause()  — no transfer restrictions
    // No admin()  — no privileged addresses
    // No upgrade  — no logic replacement mechanism
    // ──────────────────────────────────────────────────────────────────────────
}
`;

export interface OP20TemplateVars {
  name: string;
  ticker: string;
  decimals: number;
  maxSupplyHuman: string;   // e.g. "1000000000"
  iconUrl?: string;
}

/** Convert human supply to atomic units (multiply by 10^decimals) */
function toAtomicSupply(humanSupply: string, decimals: number): string {
  // Use BigInt for precision
  const base = BigInt(humanSupply);
  const factor = BigInt(10) ** BigInt(decimals);
  return (base * factor).toString();
}

/** Turn "Orange Protocol" → "OrangeProtocol" for class name */
function toClassName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("")
    .replace(/^[^a-zA-Z]/, "T"); // ensure starts with letter
}

export function generateOP20Contract(vars: OP20TemplateVars): string {
  const atomicSupply = toAtomicSupply(vars.maxSupplyHuman, vars.decimals);
  const className = toClassName(vars.name) + "Token";

  return OP20_FIXED_TEMPLATE
    .replace(/\{\{NAME\}\}/g, vars.name)
    .replace(/\{\{TICKER\}\}/g, vars.ticker)
    .replace(/\{\{DECIMALS\}\}/g, String(vars.decimals))
    .replace(/\{\{MAX_SUPPLY_ATOMIC\}\}/g, atomicSupply)
    .replace(/\{\{MAX_SUPPLY_HUMAN\}\}/g, vars.maxSupplyHuman)
    .replace(/\{\{CLASS_NAME\}\}/g, className)
    .replace(/\{\{ICON_URL\}\}/g, vars.iconUrl ?? "");
}
